#!/bin/sh
chmod 755 /usr/bin/ncdu > /dev/null 2>&1
echo "********************************************************"
echo "*  ncdu successfully installed!                        *"
echo "*                                                      *"
echo "*  ncdu is a ncurses based viewer for du               *"
echo "*  http://www.gigablue-support.org           arn354    *"
echo "********************************************************"
exit 0