#!/bin/sh
echo "********************************************************"
echo "*  ncdu successfully removed!                          *"
echo "*                                                      *"
echo "*  http://www.gigablue-support.org           arn354    *"
echo "********************************************************"
exit 0
