#!/bin/sh
TYPE=$(cat /proc/stb/info/gbmodel)
MODEL=$(cat /proc/stb/info/model)
echo "***************************************************************"
echo "  Skin MyNobile by satinfo & arn354 successfully installed on  "
echo "                      $MODEL $TYPE                             "
echo "***************************************************************"
echo " You should restart your $MODEL $TYPE now..."
echo "***************************************************************"
