#!/bin/sh
TYPE=$(cat /proc/stb/info/gbmodel)
MODEL=$(cat /proc/stb/info/model)
echo "***************************************************************"
echo "  Skin MyNobile by satinfo & arn354 will be removed from       "
echo "                      $MODEL $TYPE                             "
